/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiButton {
        "label": string;
    }
    interface UiHome {
        "first": string;
        "last": string;
    }
}
export interface UiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiButtonElement;
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiHomeElement extends Components.UiHome, HTMLStencilElement {
    }
    var HTMLUiHomeElement: {
        prototype: HTMLUiHomeElement;
        new (): HTMLUiHomeElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
        "ui-home": HTMLUiHomeElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        "label"?: string;
        "onOnClick"?: (event: UiButtonCustomEvent<any>) => void;
    }
    interface UiHome {
        "first"?: string;
        "last"?: string;
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
        "ui-home": UiHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-home": LocalJSX.UiHome & JSXBase.HTMLAttributes<HTMLUiHomeElement>;
        }
    }
}
